// Icons bundled in the self-hosted Material Symbols Outlined subset
// (FILL 0–1, wght 200, GRAD -25, opsz 24). After adding a name here, run
// `npm run icons` to download the matching font subset.
export const MATERIAL_SYMBOL_NAMES = Object.freeze([
  'account_tree',
  'add',
  'arrow_downward',
  'arrow_forward',
  'arrow_upward',
  'bookmark',
  'check',
  'check_circle',
  'close',
  'error',
  'expand_more',
  'filter_alt',
  'filter_center_focus',
  'fit_screen',
  'info',
  'inventory_2',
  'layers',
  'my_location',
  'open_in_new',
  'refresh',
  'search',
  'settings',
  'sort',
  'star',
  'swap_horiz',
  'unfold_more',
  'view_column',
  'warning',
  'zoom_in',
  'zoom_out',
]);
